# Generated by Django 3.2 on 2021-12-27 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_app', '0002_wallettransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='reference_id',
            field=models.CharField(default='1', max_length=40),
        ),
    ]
