# Generated by Django 3.2 on 2021-12-26 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='customer_xid',
            field=models.CharField(default='none', max_length=250),
            preserve_default=False,
        ),
    ]
